hashicorp/go-kms-wrapping

go.mod
wrappers/aead/aead.go
wrappers/aead/aead_test.go

This allows an existing AEAD wrapper to be used as the basis for a
derivation of a new wrapper with the key an HKDF-based derivation of the
original wrapper's key.
Eventually this also need not be the same key type, although we still
only support AES-GCM at the moment.

Add support for derived AEAD wrappers

---

wrapper.go
wrappers/multiwrapper/multiwrapper.go
wrappers/multiwrapper/multiwrapper_test.go

This wraps other wrappers by key ID. This allows you to have a workflow
similar to cloud KMSes, where you can rotate the key and the key ID is
used for decryption (even if the encryption key has changed) but for
wrappers that otherwise wouldn't support this workflow, such as AEAD or
derived AEAD wrappers.

Add multiwrapper

---

go.mod
go.sum

Adds the missing logger field from #22.
Created by running:
- `go get github.com/hashicorp/vault/sdk@5576096032f8014b30491b140416a0e53be21c59`
- `go mod tidy`

Update vault sdk to get CredentialsConfig.Logger

---

go.sum
wrapper.go
wrappers/azurekeyvault/azurekeyvault.go

This PR adds a new interface, `LifecycleWrapper`, which is a `Wrapper` that includes interface methods for lifecycle management of keys in a KMS.
A `KeyNotRequired` field has also been added to `WrapperOptions` in order to provide consumers the option to not provide an existing key when configuring a `Wrapper`. This option is useful for those who want to use `LifecycleWrapper` methods without the need of providing an existing key for cryptographic operations. `KeyNotRequired` has a default of false in order to ensure that key validation behavior continues for existing consumers of the library.
I tested this change manually by taking the following steps:
1. Bringing this branch into Vault via `go get`
2. Successfully compiling Vault
3. Configuring an `azurekeyvault` seal
4. Successfully …

Adds a new interface that includes methods for lifecycle management of keys in a KMS

---

go.mod
go.sum
wrapper.go
wrappers/azurekeyvault/azurekeyvault.go
wrappers/azurekeyvault/azurekeyvault_acc_test.go
wrappers/azurekeyvault/azurekeyvault_test.go

This PR adds an Azure Key Vault implementation of the `LifecycleWrapper` methods. This enables lifecycle management of RSA keys in Azure Key Vault using the library. See the acceptance test in this PR for an example usage of the library.
The `ImportKey` method implements the Azure Key Vault [BYOK specification](https://docs.microsoft.com/en-us/azure/key-vault/keys/byok-specification). See comments in the code for more specific details about steps in the specification.
- https://github.com/hashicorp/go-kms-wrapping/pull/25
This PR includes an acceptance test which exercises each of the `LifecycleWrapper` method implementations. This test directly interacts with Azure Key Vault APIs, so credentials are needed to run it.
Acceptance Test Output:
```sh
$ AZURE_CLIENT_ID=<redacted> …
```

Adds Azure Key Vault implementation of LifecycleWrapper methods

---

wrappers/awskms/awskms.go

This PR adds usage of the `WrapperOptions.KeyNotRequired` option to the AWS KMS wrapper. Current clients of the wrapper will not experience a behavior change, as the default value requires the key ID to be provided. This is similar to what's currently in the Azure Key Vault wrapper on [azurekeyvault.go#L46](https://github.com/hashicorp/go-kms-wrapping/blob/master/wrappers/azurekeyvault/azurekeyvault.go#L46).
Additionally, this PR adds a getter for the AWS KMS wrapper client. This is similar to what's currently in the Azure Key Vault wrapper on [azurekeyvault.go#L301](https://github.com/hashicorp/go-kms-wrapping/blob/master/wrappers/azurekeyvault/azurekeyvault.go#L301).

Use option to not require a key when configuring the AWS KMS wrapper

---

wrappers/gcpckms/gcpckms.go

This PR adds usage of the `WrapperOptions.KeyNotRequired` option to the GCP KMS wrapper. Current clients of the wrapper will not experience a behavior change, as the default value requires the crypto key to be provided. The change in this PR is similar to what was done for the [Azure Key Vault](https://github.com/hashicorp/go-kms-wrapping/blob/master/wrappers/azurekeyvault/azurekeyvault.go#L61) and [AWS KMS](https://github.com/hashicorp/go-kms-wrapping/blob/master/wrappers/awskms/awskms.go#L63) wrappers.
This PR also adds a getter for the client used by the GCP KMS wrapper.

gcpkms: add client getter and option to not provide crypto key in config

---

go.mod
go.sum
wrappers/awskms/awskms.go

These are parameters exposed by awsutil for generating credential chains
but that we don't actually allow the user to set yet.

Expose more credential config parameters

---

wrappers/gcpckms/gcpckms.go

This PR adds a method to the `gcpckms` wrapper for obtaining the [relative resource name](https://cloud.google.com/apis/design/resource_names#relative_resource_name) of the configured [Key Ring](https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings#KeyRing).

gcpckms: Adds method for getting the relative resource name of the configured key ring

---

wrappers/awskms/awskms.go
wrappers/awskms/awskms_test.go
wrappers/azurekeyvault/azurekeyvault.go
wrappers/azurekeyvault/azurekeyvault_acc_test.go

- A minimal change due to the v2 version actively being worked on to allow
Vault to specify all the configuration parameters to either an Azure or
AWS wrapper and ignore any environment variables that would be set/override 
the provided values within the config map.
- This is to allow the new Managed Key feature within Vault to specify the entire configuration 
to a wrapper and not have an existing seal wrap environment var override configuration of the 
managed key for example.
- Relates to VAULT-5067

Add the ability for a Azure/AWS wrapper to ignore environment variables

---

wrappers/awskms/awskms.go
wrappers/awskms/awskms_test.go

This adds a line to make sure that `currentKeyID` is always set when `SetConfig` is called, so that calls to the `KeyID()` function will return the correct key ID when `keyNotRequired` is `true`.

Always set currentKeyID in SetConfig

---

extras/kms/data_key.go
extras/kms/data_key_test.go
extras/kms/data_key_version.go
extras/kms/data_key_version_test.go
extras/kms/errors.go
extras/kms/go.mod
extras/kms/go.sum
extras/kms/key_purpose.go
extras/kms/kms.go
extras/kms/option.go
extras/kms/option_test.go
extras/kms/repository.go
extras/kms/repository_data_key.go
extras/kms/repository_data_key_test.go
extras/kms/repository_data_key_version.go
extras/kms/repository_data_key_version_test.go
extras/kms/repository_root_key.go
extras/kms/repository_root_key_test.go
extras/kms/repository_root_key_version.go
extras/kms/repository_root_key_version_test.go
extras/kms/repository_test.go
extras/kms/root_key.go
extras/kms/root_key_test.go
extras/kms/root_key_version.go
extras/kms/root_key_version_test.go
extras/kms/schema_test.go
extras/kms/testing.go

This PR adds the repository layer to the extras/kms module. It also adds models for DataKey and DataKeyVersion types and an additional schema test for duplicate scope ids.
Reviewers: once again the feature commits in this PR are based on work within Boundary's kms repository for reference.

feature (extras/kms): add Repository functions

---

wrappers/awskms/awskms.go

(But with an env var to override this behavior in a pinch).  This addresses
seal wrap migration problems customers are having where Vault is not able to
detect that a rewrap needs to start because the AWS wrapper is able to
decrypt the previous value with the "new" key because in fact it's using the
old key via the implicit ciphertext metadata.

Explicitly provide the KeyID to Decrypt operations

---

extras/kms/kms.go
extras/kms/option.go
extras/kms/option_test.go

It wasn't reachable from external callers anywho, and if you need
a specific reader/writer when using GetWrapper(...) then you just
need to create a new Kms with whatever reader/writer is needed.

refactor (extras/kms): remove withRepository(...) option

---

extras/kms/testing.go
extras/kms/testing_test.go

These two new test functions allow callers to either delete a specific
key purpose or all the keys for testing.

feature (extras/kms): add TestDeleteKeyPurpose, TestKmsDeleteAllKeys

---

extras/kms/kms.go
extras/kms/kms_internal_test.go
extras/kms/repository.go

We don't want to limit the lists of KEKs/DEKs by default, so if
the system has a LOT of keys it will still behave correctly.

feature (extras/kms): no limits on listings by default 

---

extras/kms/CHANGELOG.md
extras/kms/migrations/postgres/01_domain_types.up.sql
extras/kms/migrations/postgres/02_version.up.sql
extras/kms/migrations/postgres/04_keys.up.sql

This PR includes a few minor changes and a few critical schema changes.   
The critical schema changes involve:
- Explicitly naming FK and unique constraints so they can be referenced by name in the future if any changes are required.  
- Adding the `kms` prefix to the `update_time_column()` function
The minor changes were just some additional comments to existing tables.

extras/kms package: schema changes

---

extras/kms/go.mod
extras/kms/go.sum
extras/kms/kms.go
extras/kms/kms_internal_test.go
extras/kms/kms_test.go
extras/kms/migrations/fs.go
extras/kms/migrations/postgres/06_kms_collection_version.up.sql
extras/kms/migrations/sqlite/06_kms_collection_version.up.sql
extras/kms/option.go
extras/kms/repository.go
extras/kms/repository_data_key.go
extras/kms/repository_data_key_test.go
extras/kms/repository_data_key_version.go
extras/kms/repository_data_key_version_test.go
extras/kms/repository_root_key.go
extras/kms/repository_root_key_test.go
extras/kms/repository_root_key_version.go
extras/kms/repository_root_key_version_test.go
extras/kms/testing.go

Add support for versioning the entire "collection" of keys represented
by the kms.
Any time one of the keys in the collection changes, the
version will be incremented.
Adding this capability will make it easy to invalidate the kms cache.
This is especially important when the cache is shared (distributed)
across multiple processes.
This change requires incrementing the migrations version.
Given the enhancements with how the cache is handled, we're going
to always enable it, so we need to remove it as an option

refactor (extras/kms): add version to the entire kms collection and always enable the cache

---

wrappers/azurekeyvault/azurekeyvault.go

----
Backport of #97 for the next Vault 1.11.x release.

Support multiple MSI ids for Azure Key Vault (#97)

---

wrappers/awskms/awskms.go

This fixes the key ID error in using the AWS KMS v2 wrapper with managed keys

Vault-5647: fix key ID error in AWS KMS wrapper

---

extras/multi/pooled.go
extras/multi/pooledwrapper_test.go

There was a check when trying to set a duplicate wrapper using AddWrapper, but SetEncryptingWrapper was missing it. Add the check and refactor the tests to make it easier to add more tests. Add tests for the new behavior.

Prevent setting duplicate wrapper

---

wrappers/gcpckms/gcpckms.go

This is a helper function for certain GCP KMS client calls, similar to the existing `KeyRingResourceName`.

Add LocationName method to GCP wrapper to facilitate certain GCP operation calls

---

extras/crypto/options.go
extras/crypto/sha256sum.go
extras/crypto/sha256sum_test.go

Sha256SumWriter provides multi-writer which will be used to write to a hash and produce a sum.  It implements io.Writer and optionally io.Closer

feature/refactor (extras/crypto): add Sha256SumWriter and refactor sha256sum to support WithHexEncoding

---

extras/crypto/sha256sum.go
extras/crypto/sha256sum_test.go

A call to Close on a Sha256SumWriter would check if the io.MultiWriter
was an io.Closer and call Close on it. However, an io.MultiWriter does
not implement io.Closer, so the type assertion would never be true. Thus
if the initial io.Writer that is given to the Sha256SumWriter
implemented io.Closer, it would never be called.
This updates the Sha256SumWriter to keep a reference to the original
io.Writer, so it can perform the check against it and call the correct
Close. This allows Sha256SumWriter to be used as a transparent wrapper
of a io.WriteCloser.

fix(extras/crypto): Close underlying writer for Sha256SumWriter

---

.github/workflows/go.yml

Going forward: create drafts unless the push is on the main branch

fix (worklflow): fix buf push on merge

---

CODEOWNERS

For now, it assigns the entire codebase to both Vault Crypto and Boundary.

Add a codeowners file

---

extras/kms/repository.go
extras/kms/schema.go

I missed updating the schema type to support a tableNamePrefix in PR #182

fix (extras/kms): add support for tableNamePrefix to schema type

---

go.mod
go.sum
wrappers/transit/options.go
wrappers/transit/transit.go
wrappers/transit/transit_test.go

This allows Vault's seal subsystem to distinguish between two transit wrappers by passing a distinct prefix for each, but doesn't affect keyId for other consumers.

Provide a keyId prefix as an option to transit wrappers

---

.github/workflows/make-gen-delta.yml
extras/kms/Makefile
extras/kms/docs.go
extras/kms/examples/fs.go
extras/kms/key.go
extras/kms/migrations/fs.go
extras/kms/testing.go

For now this action only runs on the `extras/kms` module.

chore: add make-gen-delta action

---

.github/workflows/go.yml
examples/plugin-cli/go.mod
examples/plugin-cli/go.sum
extras/kms/examples/go.mod
extras/kms/examples/go.sum
plugin/plugin.go
plugin/plugin_common.go
plugin/plugin_js.go
wrappers/transit/go.mod
wrappers/transit/go.sum

Note that it certainly doesn't *work* under WASM, but at least it should not cause compile errors.

Allow plugin package to be compiled under WASM

---

extras/kms/kms.go
extras/kms/kms_test.go

We had an unnecessary check for an external wrappers key id before adding it to the cache.
Besides being unnecessary, the check can caused problems with external wrappers that don't determine a key id until they've completed a successful encryption operation.

fix (extras/kms): fix adding external key to cache without a key id

---

wrappers/transit/transit.go
wrappers/transit/transit_client.go
wrappers/transit/transit_test.go

This makes the transit client respect context cancelation, which is a critical feature of any I/O API.
Build failure is fixed in https://github.com/hashicorp/go-kms-wrapping/pull/260.

wrappers/transit: support context cancelation

---

wrappers/awskms/go.mod
wrappers/awskms/go.sum

This PR updates the aws-sdk-go version from `v1.44.210` to `v1.55.5` for the awskms wrapper. This PR was opened because a customer for Boundary requested the support of using EKS Pod Identity credentials. This [aws document](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html) states that the minimum required aws-sdk-go version for EKS Pod Identity credentials is Go v1 – [v1.47.11](https://github.com/aws/aws-sdk-go/releases/tag/v1.47.11)

chore: update aws sdk dep

---

wrappers/azurekeyvault/azurekeyvault.go
wrappers/azurekeyvault/main.go

The default credential provider _does_ handle managed service identities, but can only get the client id from an env var.  Supply it via env var (as there is no way in the Azure API to do so), but rely on the default credential provider to decide which auth pattern to use.

Fix incompatibility between workload identity and managed identity auth

---

.github/workflows/go.yml
.github/workflows/make-gen-delta.yml

Update all the various GitHub action plugins to the latest approved versions within tsccr.
This was done to resolve the issue I'm seeing in another PR that the build no longer works as we are using a deprecated version of actions/cache, see https://github.com/hashicorp/go-kms-wrapping/actions/runs/14196949265/job/39774240845
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: 88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8`. 
Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. 
Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
```
As newer versions of `actions/setup-go` …

Update various Github Action versions using tsccr
